# Generated by Django 3.0.6 on 2020-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
