# Generated by Django 3.0.6 on 2020-07-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='user_choice_text',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
