# Generated by Django 3.0.6 on 2020-08-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0002_auto_20200820_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user_choice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Choice'),
        ),
        migrations.AlterUniqueTogether(
            name='userchoice',
            unique_together={('question', 'user_choice')},
        ),
    ]
