# Generated by Django 3.0.6 on 2020-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0003_auto_20200821_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchoice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userchoice',
            constraint=models.UniqueConstraint(fields=('question_id', 'user_id'), name='unique_userchoice'),
        ),
    ]
