# Generated by Django 3.0.6 on 2020-07-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0004_choice_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
