# Generated by Django 3.0.6 on 2020-07-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quizzes', '0004_auto_20200630_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Choice')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
