# Generated by Django 3.0.6 on 2020-07-18 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0005_auto_20200703_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='user_question_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Question'),
            preserve_default=False,
        ),
    ]
