# Generated by Django 3.0.6 on 2020-07-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0006_userchoice_user_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='user_question_choice',
            new_name='user_choice_question',
        ),
    ]
