# Generated by Django 3.0.6 on 2020-07-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0007_auto_20200724_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Course'),
            preserve_default=False,
        ),
    ]
