# Generated by Django 3.0.6 on 2020-07-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0008_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Course'),
        ),
    ]
