# Generated by Django 3.0.6 on 2020-07-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0009_userchoice_user_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoice',
            name='user_choice_question',
        ),
    ]
