# Generated by Django 3.0.6 on 2020-07-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0010_choice_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Course'),
            preserve_default=False,
        ),
    ]
