# Generated by Django 3.0.6 on 2020-07-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0012_user_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_model',
        ),
    ]
