# Generated by Django 3.0.6 on 2020-07-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0013_delete_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Question'),
            preserve_default=False,
        ),
    ]
