# Generated by Django 3.0.6 on 2020-07-31 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0013_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usermodel',
        ),
    ]
