# Generated by Django 3.0.6 on 2020-07-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0015_userscore_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='course',
        ),
    ]
