# Generated by Django 3.0.6 on 2020-07-31 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0015_auto_20200730_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Course'),
        ),
    ]
