# Generated by Django 3.0.6 on 2020-07-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0016_auto_20200730_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Course'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.Course'),
        ),
    ]
